export const SET_GROUP_INVITES = "SET_GROUP_INVITES";
export const ADD_GROUP_INVITE = "ADD_GROUP_INVITE";
export const DELETE_GROUP_INVITE = "DELETE_GROUP_INVITE";
export const SET_GROUP_IDENTIFIER = "SET_GROUP_IDENTIFIER";
