export const START_LOADING_TIMETABLE_LESSONS =
  "START_LOADING_TIMETABLE_LESSONS";
export const SUCCESS_GET_TIMETABLE_LESSONS = "SUCCESS_GET_TIMETABLE_LESSONS";
export const FAIL_GET_TIMETABLE_LESSONS = "FAIL_GET_TIMETABLE_LESSONS";
