export const START_LOADING_TIMETABLES = "START_LOADING_TIMETABLES";
export const SUCCESS_GET_TIMETABLES = "SUCCESS_GET_TIMETABLES";
export const FAIL_GET_TIMETABLES = "FAIL_GET_TIMETABLES";
export const ADD_TIMETABLE = "ADD_TIMETABLE";
