export const START_LOADING_TIMETABLE_LESSONS =
  "START_LOADING_TIMETABLE_LESSONS";
export const FINISH_LOADING_TIMETABLE_LESSONS =
  "FINISH_LOADING_TIMETABLE_LESSONS";
export const SUCCESS_GET_TIMETABLE_LESSONS = "SUCCESS_GET_TIMETABLE_LESSONS";
export const FAIL_GET_TIMETABLE_LESSONS = "FAIL_GET_TIMETABLE_LESSONS";
export const RESET_TIMETABLE_LESSONS_ERRORS = "RESET_TIMETABLE_LESSONS_ERRORS";
export const ADD_TIMETABLE_LESSON = "ADD_TIMETABLE_LESSON";
export const DELETE_TIMETABLE_LESSON = "DELETE_TIMETABLE_LESSON";
export const SET_WEEK_DAYS_WITH_LESSONS = "SET_WEEK_DAYS_WITH_LESSONS";
