export const START_LOADING_TIMETABLE = "START_LOADING_TIMETABLE";
export const SUCCESS_GET_TIMETABLE = "SUCCESS_GET_TIMETABLE";
export const FAIL_GET_TIMETABLE = "FAIL_GET_TIMETABLE";
export const SET_WEEK_TYPES = "SET_WEEK_TYPES";
export const SET_CLASS_TIMES = "SET_CLASS_TIMES";
export const SET_TEACHERS = "SET_TEACHERS";
export const SET_SUBJECTS = "SET_SUBJECTS";
export const RESET_TIMETABLE_ERRORS = "RESET_TIMETABLE_ERRORS";
